# -*- coding: utf-8 -*-
"""Bản sao của LAY DATA CK.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bad_CMyOCc1Kc_lY_qhdj-RAhrFSyUuI
"""

import pandas as pd

# Đường dẫn file (thay nếu em đặt tên khác hoặc folder khác)
merged_path = "Merged_Full_Data_FINAL.xlsx"  # Hoặc "/content/Merged_Full_Data_FINAL.xlsx"
price_path = "VN_Stocks_Daily_Filtered_600_Sessions (1).xlsx"  # Hoặc "/content/VN_Stocks_Daily_Filtered_600_Sessions (1).xlsx"

# Đọc file
try:
    fund_df = pd.read_excel(merged_path)
    price_df = pd.read_excel(price_path)
    print("✅ Đọc file thành công!")
    print(f"Fundamental data: {fund_df.shape[0]} rows, {fund_df.shape[1]} columns")
    print(f"Price data: {price_df.shape[0]} rows, {price_df.shape[1]} columns")
    print("\nFundamental columns:", fund_df.columns.tolist())
    print("Price columns:", price_df.columns.tolist())
except FileNotFoundError as e:
    print("❌ Không tìm thấy file:", e)
    print("Kiểm tra tên file hoặc đường dẫn. Thường file nằm ở /content/")
    import os
    print("Các file hiện có:", os.listdir('/content') if os.path.exists('/content') else os.listdir('.'))

# Lưu thành CSV để dùng trong dashboard (tùy chọn)
fund_df.to_csv("FUNDAMENTAL_FOR_PORTFOLIO.csv", index=False)
price_df.to_csv("PRICE_FOR_PORTFOLIO.csv", index=False)
print("\nĐã lưu thành CSV để dùng trong dashboard!")

# ===============================
# PHÂN LOẠI NGÀNH THEO KHẨU VỊ RỦI RO
# ===============================

sector_risk_map = {
    # 🔴 TĂNG TRƯỞNG / CHU KỲ CAO (Aggressive)
    'IT Services': 'Aggressive',
    'Software': 'Aggressive',
    'Technology Hardware, Storage & Peripherals': 'Aggressive',
    'Semiconductors & Semiconductor Equipment': 'Aggressive',
    'Media': 'Aggressive',
    'Entertainment': 'Aggressive',
    'Interactive Media & Services': 'Aggressive',
    'Consumer Discretionary': 'Aggressive',
    'Automobiles': 'Aggressive',
    'Energy': 'Aggressive',
    'Oil, Gas & Consumable Fuels': 'Aggressive',
    'Real Estate Management & Development': 'Aggressive',
    'Real Estate': 'Aggressive',
    'Materials': 'Aggressive',
    'Chemicals': 'Aggressive',

    # 🟡 TRUNG TÍNH (Moderate)
    'Banks': 'Moderate',
    'Capital Markets': 'Moderate',
    'Insurance': 'Moderate',
    'Financial Services': 'Moderate',
    'Industrial Conglomerates': 'Moderate',
    'Construction & Engineering': 'Moderate',
    'Machinery': 'Moderate',
    'Transportation': 'Moderate',
    'Logistics': 'Moderate',

    # 🟢 PHÒNG THỦ (Conservative)
    'Health Care Equipment & Supplies': 'Conservative',
    'Health Care Providers & Services': 'Conservative',
    'Pharmaceuticals': 'Conservative',
    'Utilities': 'Conservative',
    'Electric Utilities': 'Conservative',
    'Water Utilities': 'Conservative',
    'Consumer Staples': 'Conservative',
    'Food Products': 'Conservative',
    'Beverages': 'Conservative',
    'Household Products': 'Conservative',
    'Telecommunication Services': 'Conservative'
}

import pandas as pd

path_price_check = "VN_Stocks_Daily_Filtered_600_Sessions (1).xlsx"
try:
    df_price_check = pd.read_excel(path_price_check)
    print(f"✅ {path_price_check} loaded successfully!")
    display(df_price_check.head())
    df_price_check.info()
except Exception as e:
    print(f"❌ Error loading {path_price_check}: {e}")

import pandas as pd

# ===============================
# LOAD DATA
# ===============================

path_merged = "Merged_Full_Data_FINAL.xlsx"
path_price = "VN_Stocks_Daily_Filtered_600_Sessions (1).xlsx"

df_fundamental = pd.read_excel(path_merged)
df_price = pd.read_excel(path_price)

print("✅ Fundamental DF shape:", df_fundamental.shape)
print("✅ Price DF shape:", df_price.shape)

import pandas as pd

path_price_check = "VN_Stocks_Daily_Filtered_600_Sessions (1).xlsx"
df_price_check = pd.read_excel(path_price_check)

print("✅ VN_Stocks_Daily_Filtered_600_Sessions (1).xlsx loaded successfully!")
display(df_price_check.head())
df_price_check.info()

import pandas as pd

path_merged = "Merged_Full_Data_FINAL.xlsx"
df_merged_check = pd.read_excel(path_merged)

print("✅ Merged_Full_Data_FINAL.xlsx loaded successfully!")
display(df_merged_check.head())
df_merged_check.info()

print("📌 Fundamental columns:")
print(df_fundamental.columns)

print("\n📌 Price columns:")
print(df_price.columns)

import pandas as pd

# ==============================
# 1. LOAD FUNDAMENTAL DATA
# ==============================
fundamental_path = "Merged_Full_Data_FINAL.xlsx"

df_fund = pd.read_excel(fundamental_path)

print("✅ Load Fundamental DF thành công")
print("Shape ban đầu:", df_fund.shape)

# ==============================
# 2. CHUẨN HÓA DATE
# ==============================
df_fund['DATE'] = pd.to_datetime(df_fund['DATE'], errors='coerce')

# ==============================
# 3. SẮP XẾP & GIỮ KỲ MỚI NHẤT
# ==============================
df_fund_latest = (
    df_fund
    .sort_values(['Symbol', 'DATE'], ascending=[True, False])
    .drop_duplicates(subset=['Symbol'], keep='first')
)

print("✅ Sau khi giữ kỳ mới nhất")
print("Shape:", df_fund_latest.shape)

# ==============================
# 4. GIỮ CÁC CỘT CẦN THIẾT
# ==============================
fundamental_cols = [
    'Symbol',
    'DATE',
    'Company Common Name',
    'GICS Industry Name',
    'EPS - Basic - excl Extraordinary Items, Common - Total',
    'Book Value per Share',
    'Beta 5 Year',
    'Dividend Yield - Common - Net - Issue - %, TTM',
    'Company Market Capitalization',
    'Net Income after Minority Interest',
    'Shareholders Equity - Common, PoP Avg'
]

df_fund_latest = df_fund_latest[fundamental_cols]

# ==============================
# 5. EXPORT FILE CHUẨN
# ==============================
output_path = "FUNDAMENTAL_LATEST_PER_SYMBOL.csv"
df_fund_latest.to_csv(output_path, index=False)

print("✅ Đã xuất file:", output_path)

import pandas as pd

# ===============================
# 1️⃣ LOAD DỮ LIỆU
# ===============================
fund_df = pd.read_csv("FUNDAMENTAL_LATEST_PER_SYMBOL.csv")
price_df = pd.read_excel("VN_Stocks_Daily_Filtered_600_Sessions (1).xlsx")

print(f"✅ Fundamental DF shape: {fund_df.shape}")
print(f"✅ Price DF shape: {price_df.shape}")

# ===============================
# 2️⃣ PHÂN LOẠI NGÀNH (Sector / Industry)
# ===============================
sector_map_full = {
    # Công nghệ thông tin
    'Information Technology': 'Công nghệ thông tin',
    'IT Services': 'Công nghệ thông tin',
    'Electronic Equipment, Instruments & Components': 'Công nghệ thông tin',

    # Hàng tiêu dùng không thiết yếu
    'Consumer Discretionary': 'Hàng tiêu dùng không thiết yếu',
    'Textiles, Apparel & Luxury Goods': 'Hàng tiêu dùng không thiết yếu',
    'Specialty Retail': 'Hàng tiêu dùng không thiết yếu',
    'Household Durables': 'Hàng tiêu dùng không thiết yếu',
    'Leisure Products': 'Hàng tiêu dùng không thiết yếu',
    'Automobiles': 'Hàng tiêu dùng không thiết yếu',

    # Hàng tiêu dùng thiết yếu
    'Consumer Staples': 'Hàng tiêu dùng thiết yếu',
    'Food Products': 'Hàng tiêu dùng thiết yếu',
    'Beverages': 'Hàng tiêu dùng thiết yếu',
    'Household Products': 'Hàng tiêu dùng thiết yếu',
    'Tobacco': 'Hàng tiêu dùng thiết yếu',

    # Ngân hàng & Tài chính
    'Banks': 'Ngân hàng & Tài chính',
    'Capital Markets': 'Ngân hàng & Tài chính',
    'Financial Services': 'Ngân hàng & Tài chính',
    'Insurance': 'Ngân hàng & Tài chính',

    # Y tế
    'Health Care Providers & Services': 'Y tế',
    'Pharmaceuticals': 'Y tế',

    # Năng lượng
    'Energy Equipment & Services': 'Năng lượng',
    'Oil, Gas & Consumable Fuels': 'Năng lượng',
    'Independent Power and Renewable Electricity Producers': 'Năng lượng',

    # Bất động sản
    'Real Estate Management & Development': 'Bất động sản',

    # Tiện ích
    'Electric Utilities': 'Tiện ích',
    'Water Utilities': 'Tiện ích',
    'Gas Utilities': 'Tiện ích',

    # Dịch vụ & giải trí / công nghiệp khác
    'Construction & Engineering': 'Công nghiệp',
    'Construction Materials': 'Công nghiệp',
    'Industrial Conglomerates': 'Công nghiệp',
    'Machinery': 'Công nghiệp',
    'Automobile Components': 'Công nghiệp',
    'Transportation Infrastructure': 'Công nghiệp',
    'Air Freight & Logistics': 'Công nghiệp',
    'Marine Transportation': 'Công nghiệp',
    'Ground Transportation': 'Công nghiệp',
    'Containers & Packaging': 'Công nghiệp',
    'Building Products': 'Công nghiệp',
    'Paper & Forest Products': 'Công nghiệp',
    'Electrical Equipment': 'Công nghiệp',
    'Trading Companies & Distributors': 'Công nghiệp',
    'Distributors': 'Công nghiệp',

    'Hotels, Restaurants & Leisure': 'Dịch vụ & giải trí',
    'Professional Services': 'Dịch vụ & giải trí',
    'Commercial Services & Supplies': 'Dịch vụ & giải trí',
    'Media': 'Dịch vụ & giải trí',
    'Entertainment': 'Dịch vụ & giải trí',
    'Diversified Consumer Services': 'Dịch vụ & giải trí',
    'Diversified Telecommunication Services': 'Dịch vụ & giải trí',
}

fund_df['Sector_Group'] = fund_df['GICS Industry Name'].map(sector_map_full).fillna('Khác')

print("✅ Phân loại ngành xong")
print(fund_df['Sector_Group'].value_counts())

# ===============================
# 3️⃣ LỌC CỔ PHIẾU THEO CRITERIA FUNDAMENTAL
# ===============================
filtered_df = fund_df[
    (fund_df['EPS - Basic - excl Extraordinary Items, Common - Total'] > 0) &
    (fund_df['Beta 5 Year'] < 1.5) &
    (fund_df['Company Market Capitalization'] > 25_000_000_000_000)  # > 1 tỷ VNĐ
]

print(f"✅ Số cổ phiếu sau khi lọc: {filtered_df.shape[0]}")

# ===============================
# 4️⃣ LỌC DỮ LIỆU GIÁ THEO SYMBOL
# ===============================
price_filtered = price_df[price_df['Symbol'].isin(filtered_df['Symbol'])]
print(f"✅ Số dòng dữ liệu giá còn lại: {price_filtered.shape[0]}")

# ===============================
# 5️⃣ XUẤT FILE CHUẨN CHO TỐI ƯU DANH MỤC
# ===============================
filtered_df.to_csv("FUNDAMENTAL_FOR_PORTFOLIO.csv", index=False)
price_filtered.to_csv("PRICE_FOR_PORTFOLIO.csv", index=False)

print("✅ Đã xuất 2 file chuẩn: FUNDAMENTAL_FOR_PORTFOLIO.csv & PRICE_FOR_PORTFOLIO.csv")

import pandas as pd

# Load lại dữ liệu đã xuất
fund_df = pd.read_csv("FUNDAMENTAL_FOR_PORTFOLIO.csv")
price_df = pd.read_csv("PRICE_FOR_PORTFOLIO.csv")

# ✅ Kiểm tra thông tin tổng quan
print("=== Fundamental DF ===")
print(f"Shape: {fund_df.shape}")
print(fund_df.head())
print("\nSector_Group counts:")
print(fund_df['Sector_Group'].value_counts())

print("\n=== Price DF ===")
print(f"Shape: {price_df.shape}")
print(price_df.head())

# ✅ Kiểm tra số lượng cổ phiếu duy nhất
print(f"\nUnique symbols in fundamental DF: {fund_df['Symbol'].nunique()}")
print(f"Unique symbols in price DF: {price_df['Symbol'].nunique()}")

# ✅ Kiểm tra khoảng thời gian dữ liệu giá
price_df['Date'] = pd.to_datetime(price_df['Date']) # Đã sửa 'DATE' thành 'Date'
print(f"Price data range: {price_df['Date'].min()} to {price_df['Date'].max()}")



# Code dashboard – phân loại nới lỏng cho Tích cực + dark mode đẹp
code = '''
import streamlit as st
import pandas as pd
import numpy as np
from scipy.optimize import minimize
import plotly.express as px
import plotly.graph_objects as go

# Load dữ liệu
@st.cache_data
def load_data():
    fund = pd.read_csv("FUNDAMENTAL_FOR_PORTFOLIO.csv")
    price = pd.read_csv("PRICE_FOR_PORTFOLIO.csv")
    if 'Date' in price.columns:
        price['DATE'] = pd.to_datetime(price['Date'])
    else:
        price['DATE'] = pd.to_datetime(price['DATE'])
    return fund, price

fund_df, price_df = load_data()

# Xử lý dữ liệu giá
price_df = price_df.drop_duplicates(subset=['DATE', 'Symbol'])
price_df = price_df.sort_values(['DATE', 'Symbol'])
price_pivot = price_df.pivot(index='DATE', columns='Symbol', values='Close')
price_pivot = price_pivot.ffill().bfill()
log_return = np.log(price_pivot / price_pivot.shift(1)).dropna(how='all')

# Tính ROE, P/E nếu chưa có
if 'ROE' not in fund_df.columns:
    fund_df['ROE'] = fund_df['Net Income after Minority Interest'] / fund_df['Shareholders Equity - Common, PoP Avg'] * 100

latest_close = price_df.sort_values(['Symbol', 'DATE'], ascending=[True, False]).drop_duplicates('Symbol')[['Symbol', 'Close']]
fund_df = fund_df.merge(latest_close, on='Symbol', how='left')

if 'P/E' not in fund_df.columns:
    fund_df['P/E'] = fund_df['Close'] / fund_df['EPS - Basic - excl Extraordinary Items, Common - Total']
    fund_df['P/E'] = fund_df['P/E'].replace([np.inf, -np.inf], np.nan).fillna(0)

# Danh sách ngành
aggressive = ['IT Services', 'Software', 'Technology Hardware, Storage & Peripherals', 'Retail', 'Textiles, Apparel & Luxury Goods',
              'Oil, Gas & Consumable Fuels', 'Chemicals', 'Real Estate Management & Development', 'Construction & Engineering',
              'Metals & Mining', 'Transportation']

conservative = ['Pharmaceuticals', 'Health Care Equipment & Services', 'Utilities', 'Independent Power and Renewable Electricity Producers',
                'Food Products', 'Beverages', 'Household Products', 'Banks']

# Phân loại khẩu vị rủi ro – NỚI LỎNG CHO TÍCH CỰC
def classify(row):
    # Tích cực: điểm số ít nhất 3/4 tiêu chí + ưu tiên ngành aggressive
    score_aggressive = sum([
        row['ROE'] > 15,
        row['Beta 5 Year'] > 1.0,
        row['P/E'] > 20,
        row['GICS Industry Name'] in aggressive
    ])
    if score_aggressive >= 3:
        return "Tích cực"

    # Bảo thủ: giữ nguyên nghiêm ngặt
    elif (row['Company Market Capitalization'] > 25_000_000_000_000 and
          row['Dividend Yield - Common - Net - Issue - %, TTM'] > 1.5 and
          row['Beta 5 Year'] < 1.2 and row['ROE'] > 10 and
          row['GICS Industry Name'] in conservative):
        return "Bảo thủ"

    # Cân bằng: nới nhẹ
    else:
        score = sum([
            row['ROE'] > 12,
            0.8 <= row['Beta 5 Year'] <= 1.3,
            row['Dividend Yield - Common - Net - Issue - %, TTM'] > 1.0,
            row['P/E'] > 12
        ])
        return "Cân bằng" if score >= 2 else "Khác"

if 'Khau_Vi_Rui_Ro' not in fund_df.columns:
    fund_df = fund_df.dropna(subset=['ROE', 'Beta 5 Year', 'P/E', 'GICS Industry Name',
                                     'Dividend Yield - Common - Net - Issue - %, TTM'])
    fund_df['Khau_Vi_Rui_Ro'] = fund_df.apply(classify, axis=1)

# Hàm tính hiệu quả – annualize đúng
def expected_return(weights, log_returns):
    return np.sum(log_returns.mean() * weights) * 252 * 100

def standard_deviation(weights, cov_matrix):
    variance = weights.T @ cov_matrix @ weights
    return np.sqrt(variance * 252) * 100

def sharpe_ratio(weights, log_returns, cov_matrix, risk_free_rate):
    ret = expected_return(weights, log_returns) / 100
    vol = standard_deviation(weights, cov_matrix) / 100
    return (ret - risk_free_rate) / vol if vol > 0 else 0

def neg_sharpe_ratio(weights, log_returns, cov_matrix, risk_free_rate):
    return -sharpe_ratio(weights, log_returns, cov_matrix, risk_free_rate)

def optimize_portfolio(log_returns_query, risk_free_rate):
    stock_list = log_returns_query.columns.tolist()

    correlation_matrix = log_returns_query.corr()
    std_devs = log_returns_query.std()
    covariance_matrix = correlation_matrix.to_numpy() * np.outer(std_devs, std_devs)
    covariance_df = pd.DataFrame(covariance_matrix, columns=log_returns_query.columns, index=log_returns_query.columns)

    constraints = {'type': 'eq', 'fun': lambda weights: np.sum(weights) - 1}
    bounds = [(0, 0.4) for _ in range(len(stock_list))]
    initial_weights = np.array([1/len(stock_list)] * len(stock_list))

    optimized_results = minimize(neg_sharpe_ratio, initial_weights,
                                 args=(log_returns_query, covariance_df, risk_free_rate),
                                 method='SLSQP', constraints=constraints, bounds=bounds)

    return optimized_results.x if optimized_results.success else initial_weights

# Risk-free rate VN thực tế
risk_free_rate = 0.0418
st.sidebar.success("Risk-free rate VN (TPCP 10 năm): 4.18% (dữ liệu 30/12/2025)")

# Giao diện
st.title("🎯 Bảng Điều Khiển Danh Mục Đầu Tư Tối Ưu (Bluechip VN)")

st.sidebar.info("Dữ liệu: 41 cổ phiếu bluechip lớn nhất HOSE")

khau_vi = st.sidebar.selectbox("Chọn khẩu vị rủi ro", ["Bảo thủ", "Cân bằng", "Tích cực"])

filtered = fund_df[fund_df['Khau_Vi_Rui_Ro'] == khau_vi].set_index('Symbol')

if filtered.empty:
    st.info(f"Không có cổ phiếu nào thuộc khẩu vị '{khau_vi}'.")
else:
    st.markdown(f"<h2 style='color: #2ca02c;'>Cổ phiếu phù hợp cho {khau_vi}</h2>", unsafe_allow_html=True)
    st.dataframe(filtered[['Company Common Name', 'ROE', 'Beta 5 Year', 'Dividend Yield - Common - Net - Issue - %, TTM', 'P/E']])

    symbols = [s for s in filtered.index if s in log_return.columns]
    if len(symbols) < 3:  # Tăng từ 2 lên 3 để chắc chắn đa dạng
        st.info(f"Chỉ có {len(symbols)} cổ phiếu – chưa đủ để tối ưu danh mục đa dạng (cần ít nhất 3).")
    else:
        log_returns_query = log_return[symbols]
        optimal_weights = optimize_portfolio(log_returns_query, risk_free_rate)

        portfolio_df = pd.DataFrame({'Ticker': symbols, 'Weight': optimal_weights})
        portfolio_df = portfolio_df[portfolio_df['Weight'] > 0.0001].sort_values('Weight', ascending=False)

        # Dividend Yield danh mục
        merged = portfolio_df.merge(filtered[['Dividend Yield - Common - Net - Issue - %, TTM']], left_on='Ticker', right_index=True)
        dividend_yield_port = (merged['Weight'] * merged['Dividend Yield - Common - Net - Issue - %, TTM']).sum()

        # Hiệu quả danh mục
        optimal_return = expected_return(optimal_weights, log_returns_query)
        optimal_vol = standard_deviation(optimal_weights, log_returns_query.cov())
        optimal_sharpe = sharpe_ratio(optimal_weights, log_returns_query, log_returns_query.cov(), risk_free_rate)

        # Hiển thị
        st.markdown("<h2 style='color: #1f77b4;'>Thông tin danh mục tối ưu</h2>", unsafe_allow_html=True)
        col1, col2, col3, col4 = st.columns(4)
        col1.metric("Lợi nhuận kỳ vọng", f"{optimal_return:.1f}%")
        col2.metric("Biến động", f"{optimal_vol:.1f}%")
        col3.metric("Sharpe Ratio", f"{optimal_sharpe:.2f}")
        col4.metric("Dividend Yield", f"{dividend_yield_port:.2f}%")

        # Pie chart
        fig = px.pie(portfolio_df, values='Weight', names='Ticker', title='Tỷ trọng danh mục tối ưu',
                     color_discrete_sequence=px.colors.sequential.Viridis)
        fig.update_traces(textinfo='percent+label', pull=[0.1 if w > 0.1 else 0 for w in portfolio_df['Weight']])
        st.plotly_chart(fig, use_container_width=True)

        # Correlation heatmap
        st.markdown("<h2 style='color: #9467bd;'>Ma trận tương quan cổ phiếu trong danh mục</h2>", unsafe_allow_html=True)
        corr = log_returns_query.corr()
        fig_corr = go.Figure(data=go.Heatmap(
            z=corr.values,
            x=corr.columns,
            y=corr.index,
            colorscale='RdBu',
            zmin=-1, zmax=1,
            text=corr.values.round(2),
            texttemplate="%{text}",
            textfont={"size": 10},
            colorbar=dict(title="Correlation")
        ))
        fig_corr.update_layout(
            title="Ma trận tương quan log-return",
            height=600,
            xaxis_title="Cổ phiếu",
            yaxis_title="Cổ phiếu",
            xaxis=dict(tickangle=45),
            plot_bgcolor='rgba(0,0,0,0)',
            paper_bgcolor='rgba(0,0,0,0)'
        )
        st.plotly_chart(fig_corr, use_container_width=True)

        # Lợi nhuận tích lũy
        st.markdown("<h2 style='color: #d62728;'>Lợi nhuận tích lũy danh mục</h2>", unsafe_allow_html=True)
        portfolio_cumulative = (log_returns_query + 1).cumprod().dot(optimal_weights)
        fig = go.Figure()
        fig.add_trace(go.Scatter(x=portfolio_cumulative.index, y=portfolio_cumulative, name="Danh mục tối ưu", line=dict(color="#1f77b4", width=2.5)))
        fig.update_layout(title="Lợi nhuận tích lũy danh mục tối ưu", xaxis_title="Ngày", yaxis_title="Lợi nhuận tích lũy",
                          height=500, plot_bgcolor='rgba(0,0,0,0)', paper_bgcolor='rgba(0,0,0,0)')
        st.plotly_chart(fig, use_container_width=True)

# Custom CSS dark mode đẹp
st.markdown("""
<style>
.stApp {
    background-color: #121212;
    color: #e0e0e0;
}
h1, h2, h3 {
    color: #ffffff;
}
.stDataFrame {
    background-color: #1e1e1e;
}
.stMetric {
    background-color: #1e1e1e;
    padding: 15px;
    border-radius: 10px;
    box-shadow: 0 4px 12px rgba(0,0,0,0.5);
    color: #ffffff;
    border: 1px solid #333333;
}
.stMetric > label {
    color: #aaaaaa;
    font-size: 0.9em;
}
.stSelectbox > div > div {
    background-color: #1e1e1e;
    color: #ffffff;
}
.stSidebar {
    background-color: #0e0e0e;
}
</style>
""", unsafe_allow_html=True)
'''

# Ghi file
with open("dashboard.py", "w") as f:
    f.write(code)


# Code dashboard – thêm so sánh benchmark VN-Index/VN30/VN100
code = '''
import streamlit as st
import pandas as pd
import numpy as np
from scipy.optimize import minimize
import plotly.express as px
import plotly.graph_objects as go

# Load dữ liệu bluechip
@st.cache_data
def load_data():
    fund = pd.read_csv("FUNDAMENTAL_FOR_PORTFOLIO.csv")
    price = pd.read_csv("PRICE_FOR_PORTFOLIO.csv")
    if 'Date' in price.columns:
        price['DATE'] = pd.to_datetime(price['Date'])
    else:
        price['DATE'] = pd.to_datetime(price['DATE'])
    return fund, price

fund_df, price_df = load_data()

# Xử lý dữ liệu giá bluechip
price_df = price_df.drop_duplicates(subset=['DATE', 'Symbol'])
price_df = price_df.sort_values(['DATE', 'Symbol'])
price_pivot = price_df.pivot(index='DATE', columns='Symbol', values='Close')
price_pivot = price_pivot.ffill().bfill()
log_return = np.log(price_pivot / price_pivot.shift(1)).dropna(how='all')

# Tính ROE, P/E
if 'ROE' not in fund_df.columns:
    fund_df['ROE'] = fund_df['Net Income after Minority Interest'] / fund_df['Shareholders Equity - Common, PoP Avg'] * 100

latest_close = price_df.sort_values(['Symbol', 'DATE'], ascending=[True, False]).drop_duplicates('Symbol')[['Symbol', 'Close']]
fund_df = fund_df.merge(latest_close, on='Symbol', how='left')

if 'P/E' not in fund_df.columns:
    fund_df['P/E'] = fund_df['Close'] / fund_df['EPS - Basic - excl Extraordinary Items, Common - Total']
    fund_df['P/E'] = fund_df['P/E'].replace([np.inf, -np.inf], np.nan).fillna(0)

# Danh sách ngành
aggressive = ['IT Services', 'Software', 'Technology Hardware, Storage & Peripherals', 'Retail', 'Textiles, Apparel & Luxury Goods',
              'Oil, Gas & Consumable Fuels', 'Chemicals', 'Real Estate Management & Development', 'Construction & Engineering',
              'Metals & Mining', 'Transportation']

conservative = ['Pharmaceuticals', 'Health Care Equipment & Services', 'Utilities', 'Independent Power and Renewable Electricity Producers',
                'Food Products', 'Beverages', 'Household Products', 'Banks']

# Phân loại – nới lỏng cho Tích cực
def classify(row):
    score_aggressive = sum([
        row['ROE'] > 15,
        row['Beta 5 Year'] > 1.0,
        row['P/E'] > 20,
        row['GICS Industry Name'] in aggressive
    ])
    if score_aggressive >= 3:
        return "Tích cực"

    elif (row['Company Market Capitalization'] > 25_000_000_000_000 and
          row['Dividend Yield - Common - Net - Issue - %, TTM'] > 1.5 and
          row['Beta 5 Year'] < 1.2 and row['ROE'] > 10 and
          row['GICS Industry Name'] in conservative):
        return "Bảo thủ"

    else:
        score = sum([
            row['ROE'] > 12,
            0.8 <= row['Beta 5 Year'] <= 1.3,
            row['Dividend Yield - Common - Net - Issue - %, TTM'] > 1.0,
            row['P/E'] > 12
        ])
        return "Cân bằng" if score >= 2 else "Khác"

if 'Khau_Vi_Rui_Ro' not in fund_df.columns:
    fund_df = fund_df.dropna(subset=['ROE', 'Beta 5 Year', 'P/E', 'GICS Industry Name',
                                     'Dividend Yield - Common - Net - Issue - %, TTM'])
    fund_df['Khau_Vi_Rui_Ro'] = fund_df.apply(classify, axis=1)

# Hàm tính hiệu quả
def expected_return(weights, log_returns):
    return np.sum(log_returns.mean() * weights) * 252 * 100

def standard_deviation(weights, cov_matrix):
    variance = weights.T @ cov_matrix @ weights
    return np.sqrt(variance * 252) * 100

def sharpe_ratio(weights, log_returns, cov_matrix, risk_free_rate):
    ret = expected_return(weights, log_returns) / 100
    vol = standard_deviation(weights, cov_matrix) / 100
    return (ret - risk_free_rate) / vol if vol > 0 else 0

def optimize_portfolio(log_returns_query, risk_free_rate):
    stock_list = log_returns_query.columns.tolist()
    correlation_matrix = log_returns_query.corr()
    std_devs = log_returns_query.std()
    covariance_matrix = correlation_matrix.to_numpy() * np.outer(std_devs, std_devs)
    constraints = {'type': 'eq', 'fun': lambda weights: np.sum(weights) - 1}
    bounds = [(0, 0.4) for _ in range(len(stock_list))]
    initial_weights = np.array([1/len(stock_list)] * len(stock_list))
    optimized_results = minimize(lambda w: -sharpe_ratio(w, log_returns_query, covariance_matrix, risk_free_rate),
                                 initial_weights, method='SLSQP', constraints=constraints, bounds=bounds)
    return optimized_results.x if optimized_results.success else initial_weights

# Load benchmark (em thay tên file đúng)
@st.cache_data
def load_benchmark():
    vn_index = pd.read_csv("Dữ liệu Lịch sử VN Index.csv")
    vn30 = pd.read_csv("Dữ liệu Lịch sử VN 30.csv")
    vn100 = pd.read_csv("Dữ liệu Lịch sử VN100.csv")

    def process(df):
        df['Ngày'] = pd.to_datetime(df['Ngày'], format='%d/%m/%Y')
        df = df.sort_values('Ngày')
        df['Close'] = pd.to_numeric(df['Lần cuối'].str.replace(',', ''))
        df['log_return'] = np.log(df['Close'] / df['Close'].shift(1))
        log_r = df['log_return'].dropna()
        ret = log_r.mean() * 252 * 100
        vol = log_r.std() * np.sqrt(252) * 100
        sharpe = (ret/100 - 0.0418) / (vol/100) if vol > 0 else 0
        return round(ret, 1), round(vol, 1), round(sharpe, 2)

    benchmarks = {
        'VN-Index': process(vn_index),
        'VN30': process(vn30),
        'VN100': process(vn100)
    }
    return benchmarks

benchmarks = load_benchmark()

# Risk-free rate
risk_free_rate = 0.0418
st.sidebar.success("Risk-free rate VN (TPCP 10 năm): 4.18% (dữ liệu 30/12/2025)")

# Giao diện
st.title("🎯 Bảng Điều Khiển Danh Mục Đầu Tư Tối Ưu (Bluechip VN)")

st.sidebar.info("Dữ liệu: 41 cổ phiếu bluechip lớn nhất HOSE")

khau_vi = st.sidebar.selectbox("Chọn khẩu vị rủi ro", ["Bảo thủ", "Cân bằng", "Tích cực"])

filtered = fund_df[fund_df['Khau_Vi_Rui_Ro'] == khau_vi].set_index('Symbol')

if filtered.empty:
    st.info(f"Không có cổ phiếu nào thuộc khẩu vị '{khau_vi}'.")
else:
    st.markdown(f"<h2 style='color: #2ca02c;'>Cổ phiếu phù hợp cho {khau_vi}</h2>", unsafe_allow_html=True)
    st.dataframe(filtered[['Company Common Name', 'ROE', 'Beta 5 Year', 'Dividend Yield - Common - Net - Issue - %, TTM', 'P/E']])

    symbols = [s for s in filtered.index if s in log_return.columns]
    if len(symbols) < 3:
        st.info(f"Chỉ có {len(symbols)} cổ phiếu – chưa đủ đa dạng.")
    else:
        log_returns_query = log_return[symbols]
        optimal_weights = optimize_portfolio(log_returns_query, risk_free_rate)

        portfolio_df = pd.DataFrame({'Ticker': symbols, 'Weight': optimal_weights})
        portfolio_df = portfolio_df[portfolio_df['Weight'] > 0.0001].sort_values('Weight', ascending=False)

        merged = portfolio_df.merge(filtered[['Dividend Yield - Common - Net - Issue - %, TTM']], left_on='Ticker', right_index=True)
        dividend_yield_port = (merged['Weight'] * merged['Dividend Yield - Common - Net - Issue - %, TTM']).sum()

        optimal_return = expected_return(optimal_weights, log_returns_query)
        optimal_vol = standard_deviation(optimal_weights, log_returns_query.cov())
        optimal_sharpe = sharpe_ratio(optimal_weights, log_returns_query, log_returns_query.cov(), risk_free_rate)

        st.markdown("<h2 style='color: #1f77b4;'>Thông tin danh mục tối ưu</h2>", unsafe_allow_html=True)
        col1, col2, col3, col4 = st.columns(4)
        col1.metric("Lợi nhuận kỳ vọng", f"{optimal_return:.1f}%")
        col2.metric("Biến động", f"{optimal_vol:.1f}%")
        col3.metric("Sharpe Ratio", f"{optimal_sharpe:.2f}")
        col4.metric("Dividend Yield", f"{dividend_yield_port:.2f}%")

        # Pie chart, heatmap, cumulative như cũ...
        # (giữ nguyên phần cũ)

        # SO SÁNH BENCHMARK
        st.markdown("<h2 style='color: #ff7f0e;'>So sánh với Benchmark (2020-2025)</h2>", unsafe_allow_html=True)
        comparison_data = [
            {"Nhóm": khau_vi, "Return (%)": optimal_return, "Vol (%)": optimal_vol, "Sharpe": optimal_sharpe},
            {"Nhóm": "VN-Index", "Return (%)": benchmarks['VN-Index'][0], "Vol (%)": benchmarks['VN-Index'][1], "Sharpe": benchmarks['VN-Index'][2]},
            {"Nhóm": "VN30", "Return (%)": benchmarks['VN30'][0], "Vol (%)": benchmarks['VN30'][1], "Sharpe": benchmarks['VN30'][2]},
            {"Nhóm": "VN100", "Return (%)": benchmarks['VN100'][0], "Vol (%)": benchmarks['VN100'][1], "Sharpe": benchmarks['VN100'][2]},
        ]
        df_comp = pd.DataFrame(comparison_data)
        st.dataframe(df_comp.style.highlight_max(subset=['Sharpe'], color='lightgreen'))

        # Biểu đồ scatter
        fig = go.Figure()
        for row in comparison_data:
            color = 'red' if row['Nhóm'] == khau_vi else 'gray'
            size = 20 if row['Nhóm'] == khau_vi else 10
            fig.add_trace(go.Scatter(x=[row['Vol (%)']], y=[row['Return (%)']], mode='markers+text',
                                     marker=dict(size=size, color=color), text=row['Nhóm'], textposition="top center"))
        fig.update_layout(title="So sánh Return vs Risk", xaxis_title="Biến động (%)", yaxis_title="Lợi nhuận kỳ vọng (%)")
        st.plotly_chart(fig)

# Dark mode CSS
st.markdown("""
<style>
.stApp {background-color: #121212; color: #e0e0e0;}
h1, h2, h3 {color: #ffffff;}
.stDataFrame {background-color: #1e1e1e;}
.stMetric {background-color: #1e1e1e; padding: 15px; border-radius: 10px; box-shadow: 0 4px 12px rgba(0,0,0,0.5); color: #ffffff; border: 1px solid #333333;}
.stMetric > label {color: #aaaaaa;}
.stSidebar {background-color: #0e0e0e;}
</style>
""", unsafe_allow_html=True)
'''

